site_name: Aviation Model
theme:
  name: material

markdown_extensions:
  - pymdownx.caret
  - pymdownx.tilde
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Home: "index.md"
  - Aviation Model: "aviation.md"
